spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema-transicion
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: create
  main:
    allow-bean-definition-overriding: true
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8964 
      
      
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000